
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kakao_pay?serverTimezone=Asia/Seoul
    username: pjm
    password: jmjm1102
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
payment:
  toss:
    clientKey: test_ck_Z61JOxRQVE17jJlvJlyVW0X9bAqw
    secretKey: "test_sk_0RnYX2w532ByROzq0ZK3NeyqApQE"
    success_url: "http://localhost:8080/payment/success"
    fail_url: "http://localhost:8080/payment/fail"
